# Generated by Django 5.0.4 on 2024-04-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch',
            new_name='school',
        ),
    ]
