# Generated by Django 5.0.4 on 2024-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_rename_batch_batch_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.CharField(choices=[('MCA', 'mca'), ('MBA', 'mba')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
